import React, { useEffect, useState } from "react";
import PlaceInput from "../components/PlaceInput";
import { UTILITY_CALCULATORS } from "../data/utility-calculators";
import { quickBirth, mangalDosha, kalaSarpa, sadeSati, shraddhaTithi, panchaPakshi, westernNatal, westernRelationship } from "../engine/utility-calculators";
import { zoneOffset } from "../engine/panchang";

const METHODS:Record<string,{en:string;hi:string}> = {
  rashi:{en:"Lahiri sidereal Moon sign.",hi:"लाहिरी निरयन चन्द्र राशि।"}, "sun-sign":{en:"Lahiri sidereal Sun sign—not the tropical newspaper sign.",hi:"लाहिरी निरयन सूर्य राशि—सायन राशि नहीं।"},
  lagna:{en:"Lahiri sidereal ascendant from exact time and place.",hi:"सटीक समय-स्थान से लाहिरी निरयन लग्न।"}, nakshatra:{en:"Moon divided into 27 equal nakshatras and four padas.",hi:"चन्द्र-पथ के 27 समान नक्षत्र और चार चरण।"},
  "baby-name":{en:"Traditional nakshatra-pada sound; spelling may follow the family's language.",hi:"नक्षत्र-चरण का पारम्परिक नामाक्षर; वर्तनी पारिवारिक भाषा के अनुसार हो सकती है।"},
  "mangal-dosha":{en:"Mars in houses 1, 2, 4, 7, 8 or 12, checked separately from Lagna, Moon and Venus. Mitigations are shown but do not silently erase a result.",hi:"लग्न, चन्द्र और शुक्र—तीनों से मंगल का 1, 2, 4, 7, 8 या 12 भाव; शमन को अलग दिखाया गया है।"},
  "kala-sarpa":{en:"Strict geometric convention: all seven classical planets must be inside one Rahu–Ketu semicircle. This is a pattern, not a prediction of harm.",hi:"कठोर ज्यामितीय नियम: सातों ग्रह राहु–केतु के एक अर्धवृत्त में हों। यह योग-रचना है, अनिष्ट की भविष्यवाणी नहीं।"},
  "sade-sati":{en:"Saturn in the 12th, same or 2nd sign from the natal Moon. Results are descriptive, not deterministic.",hi:"जन्म चन्द्र से शनि की 12वीं, उसी या दूसरी राशि। फल निश्चित नहीं माना गया है।"},
  "shraddha-tithi":{en:"The lunar tithi and paksha at the recorded time; annual observance selection uses the corresponding tithi with local aparahna precedence.",hi:"दिए समय की तिथि और पक्ष; वार्षिक श्राद्ध में उसी तिथि और स्थानीय अपराह्न को प्रधानता।"},
  "pancha-pakshi":{en:"Birth-bird mapping from nakshatra group and waxing/waning fortnight. Lineage-specific sub-yama schedules are intentionally not invented.",hi:"नक्षत्र-समूह और शुक्ल/कृष्ण पक्ष से जन्म-पक्षी; परम्परा-विशिष्ट सूक्ष्म समय अनुमान से नहीं जोड़े गए।"},
  "western-natal":{en:"Western method: tropical zodiac and major Ptolemaic aspects. It is kept separate from Ganak's Vedic Lahiri defaults.",hi:"पाश्चात्य पद्धति: सायन राशि और प्रमुख टॉलेमिक दृष्टियाँ; गणक की वैदिक लाहिरी पद्धति से अलग।"},
  "western-relationship":{en:"Western tropical synastry plus a shortest-arc midpoint composite; relationship themes are not compatibility verdicts.",hi:"पाश्चात्य सायन सिनैस्ट्री और न्यूनतम-चाप मध्य-बिन्दु कम्पोज़िट; यह सम्बन्ध का अंतिम निर्णय नहीं।"},
};

function InputSet({value,onChange,place,onPlace,onConfirmed,C,lang,labels}:any){const hi=lang==="hi";const dateLabel=labels?labels.date:(hi?"तिथि":"Date");const timeLabel=labels?labels.time:(hi?"समय":"Time");return <div style={{display:"grid",gap:10}}>
  <label>{dateLabel}<input type="date" value={value.date} onChange={e=>onChange({...value,date:e.target.value})} style={input(C)}/></label>
  <label>{timeLabel}<input type="time" value={value.time} onChange={e=>onChange({...value,time:e.target.value})} style={input(C)}/></label>
  <label>{hi?"स्थान":"Place"}<PlaceInput value={place} onPick={onPlace} onConfirmed={onConfirmed} C={C} lang={lang}/></label>
  </div>}
const input=(C:any)=>({display:"block",width:"100%",height:42,marginTop:5,border:`1px solid ${C.line}`,borderRadius:11,padding:"0 11px",background:"#FFFDF7",color:C.ivory});
function makeInput(v:any,place:any){const [y,m,day]=v.date.split("-").map(Number),[hh,mi]=v.time.split(":").map(Number);const tz=zoneOffset(place.zone,y,m,day)??5.5;return {y,m,day,hh,mi,tz,lat:place.lat,lon:place.lon};}
const SIGN_HI:Record<string,string>={Aries:"मेष",Taurus:"वृषभ",Gemini:"मिथुन",Cancer:"कर्क",Leo:"सिंह",Virgo:"कन्या",Libra:"तुला",Scorpio:"वृश्चिक",Sagittarius:"धनु",Capricorn:"मकर",Aquarius:"कुम्भ",Pisces:"मीन"};
const PLANET_HI:Record<string,string>={Sun:"सूर्य",Moon:"चन्द्र",Mercury:"बुध",Venus:"शुक्र",Mars:"मंगल",Jupiter:"गुरु",Saturn:"शनि"};
const ASPECT_HI:Record<string,string>={Conjunction:"युति",Sextile:"षडाष्टक",Square:"केन्द्र-दृष्टि",Trine:"त्रिकोण",Opposition:"प्रतियुति"};
const TERM_HI:Record<string,string>={Dhanishta:"धनिष्ठा",Shatabhisha:"शतभिषा",Ashwini:"अश्विनी",Bharani:"भरणी",Krittika:"कृत्तिका",Rohini:"रोहिणी",Mrigashira:"मृगशिरा",Ardra:"आर्द्रा",Punarvasu:"पुनर्वसु",Pushya:"पुष्य",Ashlesha:"आश्लेषा",Magha:"मघा","Purva Phalguni":"पूर्व फाल्गुनी","Uttara Phalguni":"उत्तर फाल्गुनी",Hasta:"हस्त",Chitra:"चित्रा",Swati:"स्वाती",Vishakha:"विशाखा",Anuradha:"अनुराधा",Jyeshtha:"ज्येष्ठा",Mula:"मूल","Purva Ashadha":"पूर्वाषाढ़ा","Uttara Ashadha":"उत्तराषाढ़ा",Shravana:"श्रवण","Purva Bhadrapada":"पूर्व भाद्रपदा","Uttara Bhadrapada":"उत्तर भाद्रपदा",Revati:"रेवती",Shukla:"शुक्ल",Krishna:"कृष्ण",Chaitra:"चैत्र",Vaishakha:"वैशाख",JyeshthaMonth:"ज्येष्ठ",Ashadha:"आषाढ़",ShravanaMonth:"श्रावण",Bhadrapada:"भाद्रपद",Ashwina:"आश्विन",Kartika:"कार्तिक",Margashirsha:"मार्गशीर्ष",Pausha:"पौष",MaghaMonth:"माघ",Phalguna:"फाल्गुन",Pratipada:"प्रतिपदा",Dwitiya:"द्वितीया",Tritiya:"तृतीया",Chaturthi:"चतुर्थी",Panchami:"पञ्चमी",Shashthi:"षष्ठी",Saptami:"सप्तमी",Ashtami:"अष्टमी",Navami:"नवमी",Dashami:"दशमी",Ekadashi:"एकादशी",Dwadashi:"द्वादशी",Trayodashi:"त्रयोदशी",Chaturdashi:"चतुर्दशी",Purnima:"पूर्णिमा",Amavasya:"अमावस्या"};
const localTerm=(value:string,hi:boolean)=>hi?(TERM_HI[value]||value):value;
const signOnly=(value:string,hi:boolean)=>{const western=value.match(/\(([^)]+)\)/)?.[1]||value;return hi?(SIGN_HI[western]||value.split(" (")[0]):western;};
const westernSign=(value:string,hi:boolean)=>hi?(SIGN_HI[value]||value):value;

export default function UtilityCalculatorScreen({route,lang,C,card,place,onPlace}:any){
  const hi=lang==="hi", today=new Date().toISOString().slice(0,10), [birth,setBirth]=useState({date:"1990-01-01",time:"12:00"}),[second,setSecond]=useState({date:"1992-01-01",time:"12:00"}),[asOf,setAsOf]=useState(today),[result,setResult]=useState<any>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
  // Person A uses the shell's shared place (identical to single-person behaviour).
  // Person B has its own independent place so changing one never changes the other.
  const [placeB,setPlaceB]=useState<any>(place);
  const [confirmedA,setConfirmedA]=useState(true),[confirmedB,setConfirmedB]=useState(true);
  const item=route.kind==="calculator"?route.calculator:null;
  const notFound=route.kind==="notfound";
  useEffect(()=>{
    const title=notFound?(hi?"कैलकुलेटर नहीं मिला | Ganak":"Calculator not found | Ganak"):item?`${hi?item.hi:item.en} | Ganak`:`${hi?"ज्योतिष कैलकुलेटर":"Astrology calculators"} | Ganak`;
    document.title=title;
    let meta=document.querySelector('meta[name="description"]') as HTMLMetaElement|null;if(!meta){meta=document.createElement("meta");meta.name="description";document.head.appendChild(meta);}
    meta.content=notFound?(hi?"अनुरोधित कैलकुलेटर उपलब्ध नहीं है। सभी उपलब्ध कैलकुलेटर देखें।":"The requested calculator is not available. See all available calculators."):item?(hi?item.blurbHi:item.blurbEn):(hi?"गणक के वैदिक और पाश्चात्य ज्योतिष कैलकुलेटर":"Ganak's Vedic and Western astrology calculators");
    let canonical=document.querySelector('link[rel="canonical"]') as HTMLLinkElement|null;if(!canonical){canonical=document.createElement("link");canonical.rel="canonical";document.head.appendChild(canonical);}
    // Unknown calculators canonicalise to the catalogue, not to their own invalid URL.
    canonical.href=location.origin+(item?`/calculator/${item.slug}`:"/calculators");
  },[item,hi,notFound]);
  if(notFound)return <div><h2 style={{fontFamily:"Eczar,serif",color:C.gold}}>{hi?"यह कैलकुलेटर उपलब्ध नहीं है":"This calculator isn't available"}</h2><p style={{color:C.muted}}>{hi?"आपने जो कैलकुलेटर खोला वह गणक में मौजूद नहीं है। नीचे से सभी उपलब्ध कैलकुलेटर देखें।":"The calculator you opened doesn't exist in Ganak. Browse all the available calculators below."}</p><a href={`/calculators?lang=${lang}`} style={{...card,display:"inline-block",padding:"12px 18px",textDecoration:"none",color:C.gold,fontWeight:700}}>{hi?"सभी कैलकुलेटर देखें →":"See all calculators →"}</a></div>;
  if(route.kind==="catalogue")return <div><h2 style={{fontFamily:"Eczar,serif",color:C.gold}}>{hi?"ज्योतिष कैलकुलेटर":"Astrology calculators"}</h2><p style={{color:C.muted}}>{hi?"वैदिक और पाश्चात्य विधियाँ स्पष्ट रूप से अलग रखी गई हैं।":"Choose a focused answer. Vedic and Western methods are clearly separated."}</p>{["vedic","western"].map(group=><section key={group}><h3>{group==="vedic"?(hi?"वैदिक · लाहिरी":"VEDIC · LAHIRI"):(hi?"पाश्चात्य · सायन":"WESTERN · TROPICAL")}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}>{UTILITY_CALCULATORS.filter(x=>x.group===group).map(x=><a key={x.slug} href={`/calculator/${x.slug}?lang=${lang}`} style={{...card,padding:16,textDecoration:"none",color:C.ivory}}><strong style={{color:C.gold}}>{hi?x.hi:x.en}</strong><p style={{margin:"6px 0 0",color:C.muted,fontSize:14}}>{hi?x.blurbHi:x.blurbEn}</p></a>)}</div></section>)}</div>;
  const calculate=()=>{
    setError("");setNotice("");
    // Never calculate with a stale/blank/unconfirmed place.
    if(!confirmedA||!place){setResult(null);setError(hi?"गणना से पहले सुझावों में से एक स्थान चुनें।":"Choose a place from the suggestions before calculating.");return;}
    if(item.slug==="western-relationship"&&(!confirmedB||!placeB)){setResult(null);setError(hi?"दूसरे व्यक्ति के लिए सुझावों में से एक स्थान चुनें।":"Choose a place from the suggestions for the second person.");return;}
    try{
      const a=makeInput(birth,place);let r:any;
      switch(item.slug){
        case"mangal-dosha":r=mangalDosha(a);break;
        case"kala-sarpa":r=kalaSarpa(a);break;
        case"sade-sati":r=sadeSati(a,Date.parse(`${asOf}T12:00:00Z`));break;
        case"shraddha-tithi":r=shraddhaTithi(a);if(r.future){setResult(null);setNotice(hi?"श्राद्ध तिथि केवल दिवंगत व्यक्ति के लिए निकाली जाती है। कृपया दर्ज की गई तिथि और समय देखें।":"A Shraddha date is calculated only for someone who has passed. Please check the date and time entered.");return;}break;
        case"pancha-pakshi":r=panchaPakshi(a);break;
        case"western-natal":r=westernNatal(a);break;
        case"western-relationship":r=westernRelationship(a,makeInput(second,placeB));break;
        default:r=quickBirth(a);
      }
      setResult(r);
    }catch(e:any){setResult(null);setError(hi?"गणना नहीं हो सकी। तिथि, समय और स्थान जाँचें।":"Could not calculate. Check the date, time and place.");}
  };
  const answer=()=>{if(!result)return null;const q=result;if(item.slug==="rashi")return hi?`आपकी चन्द्र राशि ${signOnly(q.rashi,true)} है।`:`Your Moon sign is ${signOnly(q.rashi,false)}.`;if(item.slug==="sun-sign")return hi?`आपकी वैदिक सूर्य राशि ${signOnly(q.sunSign,true)} है।`:`Your Vedic Sun sign is ${signOnly(q.sunSign,false)}.`;if(item.slug==="lagna")return hi?`आपका लग्न ${signOnly(q.lagna,true)} है।`:`Your ascendant is ${signOnly(q.lagna,false)}.`;if(item.slug==="nakshatra")return `${hi?"आपका जन्म नक्षत्र":"Your birth nakshatra is"} ${localTerm(q.nakshatra,hi)}, ${hi?"चरण":"pada"} ${q.pada}.`;if(item.slug==="baby-name")return `${hi?"सुझाया नामाक्षर":"Suggested starting sound"}: ${hi?q.syllableHi:q.syllable}`;if(item.slug==="mangal-dosha")return q.present?(hi?`मंगल दोष ${q.strength==="strong"?"प्रबल":q.strength==="moderate"?"मध्यम":"सीमित"} रूप में मिला।`:`Mangal Dosha is present at ${q.strength} strength.`):(hi?"तीनों सन्दर्भों से मंगल दोष नहीं मिला।":"Mangal Dosha is not found from the three references.");if(item.slug==="kala-sarpa")return q.present?(hi?"कठोर ज्यामितीय नियम से काल सर्प रचना मिलती है।":"The strict geometric Kala Sarpa pattern is present."):(hi?`पूर्ण काल सर्प रचना नहीं मिली; ${q.enclosed}/7 ग्रह एक ओर हैं।`:`No complete Kala Sarpa pattern; ${q.enclosed}/7 planets are enclosed.`);if(item.slug==="sade-sati")return q.active?(hi?`साढ़ेसाती का ${q.phase==="rising"?"आरम्भिक":q.phase==="middle"?"मध्य":"अन्तिम"} चरण चल रहा है।`:`Sade Sati is active in its ${q.phase} phase.`):(hi?"चुनी तिथि पर साढ़ेसाती सक्रिय नहीं है।":"Sade Sati is not active on the selected date.");if(item.slug==="shraddha-tithi"){const a=q.annual?.[0],month=q.amanta.replace(" (Adhik)","");return `${localTerm(month,hi)} ${localTerm(q.fortnight,hi)} ${localTerm(q.tithi,hi)} (${q.number})${a?` · ${hi?"वार्षिक श्राद्ध तिथि":"calculated annual date"}: ${a.day}/${a.month}/${a.year}`:""}`;}if(item.slug==="pancha-pakshi")return `${hi?"आपका जन्म-पक्षी":"Your birth bird"}: ${hi?q.birdHi:q.bird}.`;if(item.slug==="western-natal")return hi?`आपकी मुख्य राशियाँ: सूर्य ${westernSign(q.bigThree.sun,true)} · चन्द्र ${westernSign(q.bigThree.moon,true)} · उदय ${westernSign(q.bigThree.ascendant,true)}।`:`Your Big Three: ${q.bigThree.sun} Sun · ${q.bigThree.moon} Moon · ${q.bigThree.ascendant} Rising.`;return `${hi?"प्रमुख सिनैस्ट्री सम्बन्ध":"Strongest synastry contacts"}: ${q.contacts.slice(0,3).map((x:any)=>hi?`${PLANET_HI[x.one]}–${PLANET_HI[x.two]} ${ASPECT_HI[x.name]}`:`${x.one}–${x.two} ${x.name}`).join(" · ")|| (hi?"कोई निकट प्रमुख दृष्टि नहीं":"no close major aspects")}.`;};
  const detail=()=>{const q=result;if(item.slug==="mangal-dosha")return q.refs.map((x:any)=>`${hi?({Lagna:"लग्न",Moon:"चन्द्र",Venus:"शुक्र"} as any)[x.key]:x.key}: ${hi?"भाव":"house"} ${x.house} — ${x.counted?(hi?"गणना में":"counted"):(hi?"गणना से बाहर":"not counted")}`).join(" · ");if(item.slug==="sade-sati")return `${hi?"जन्म चन्द्र":"Natal Moon"}: ${signOnly(q.moonSign,hi)} · ${hi?"वर्तमान शनि":"Saturn"}: ${signOnly(q.saturnSign,hi)}`;if(item.slug==="western-natal")return `${q.aspects.length} ${hi?"प्रमुख दृष्टियाँ मिलीं":"major aspects found"}`;if(item.slug==="western-relationship")return `${q.contacts.length} ${hi?"निकट सिनैस्ट्री सम्बन्ध मिले":"close synastry contacts found"}`;return hi?"गणना ऊपर दी गई पद्धति के अनुसार पूरी हुई।":"Calculation completed under the stated convention.";};
  return <div><a href={`/calculators?lang=${lang}`} style={{color:C.gold}}>← {hi?"सभी कैलकुलेटर":"All calculators"}</a><h2 style={{fontFamily:"Eczar,serif",color:C.gold,marginBottom:4}}>{hi?item.hi:item.en}</h2><p style={{color:C.muted,marginTop:0}}>{hi?item.blurbHi:item.blurbEn}</p><div style={{...card,padding:18}}><InputSet value={birth} onChange={setBirth} place={place} onPlace={onPlace} onConfirmed={setConfirmedA} labels={item.slug==="shraddha-tithi"?{date:hi?"निधन की तिथि":"Date of passing",time:hi?"निधन का समय":"Time of passing"}:undefined} C={C} lang={lang}/>{item.slug==="western-relationship"&&<><h3>{hi?"दूसरा व्यक्ति":"Second person"}</h3><InputSet value={second} onChange={setSecond} place={placeB} onPlace={setPlaceB} onConfirmed={setConfirmedB} C={C} lang={lang}/></>}{item.slug==="sade-sati"&&<label style={{display:"block",marginTop:10}}>{hi?"किस तिथि के लिए":"Check date"}<input type="date" value={asOf} onChange={e=>setAsOf(e.target.value)} style={input(C)}/></label>}<button className="castBtn" onClick={calculate} style={{height:42,marginTop:16,width:"100%",border:0,borderRadius:11,background:C.gold,color:"white",fontWeight:700}}>{hi?"गणना करें":"Calculate"}</button>{error&&<p role="alert" style={{color:C.sindoor}}>{error}</p>}{notice&&<p role="status" style={{color:C.muted,marginTop:10}}>{notice}</p>}</div>{result&&<><section style={{...card,padding:18,marginTop:14,borderLeft:`4px solid ${C.gold}`}}><small style={{color:C.muted}}>{hi?"सीधा उत्तर":"ANSWER FIRST"}</small><h3 style={{margin:"7px 0"}}>{answer()}</h3></section><details style={{...card,padding:16,marginTop:12}}><summary style={{cursor:"pointer",color:C.gold}}>{hi?"गणना का विवरण":"Calculation details"}</summary><p style={{fontSize:14}}>{detail()}</p></details></>}<section style={{marginTop:18,padding:14,borderTop:`1px solid ${C.line}`}}><strong>{hi?"पद्धति और सीमा":"Method & limits"}</strong><p style={{color:C.muted,fontSize:14}}>{hi?METHODS[item.slug].hi:METHODS[item.slug].en}</p><small style={{color:C.muted}}>{hi?"स्रोत-सार: गणक पद्धति मानचित्र में शास्त्रीय/प्रकाशित आधार दर्ज हैं।":"Source note: classical and published bases are recorded in Ganak's method map."}</small></section></div>;
}
