import fs from "node:fs";
import path from "node:path";
import { publicRoutes, legacyRedirects, origin, ROOT } from "./seo-routes.mjs";

const DIST = path.join(ROOT, "dist");

function writeFile(relative, contents) {
  const target = path.join(DIST, relative);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents, "utf8");
}

function xmlEscape(value) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function emitSitemap(routes) {
  const seen = new Set();
  const locs = [];
  for (const route of routes) {
    if (seen.has(route.canonicalPath)) continue;
    seen.add(route.canonicalPath);
    locs.push(`  <url><loc>${xmlEscape(origin() + route.canonicalPath)}</loc></url>`);
  }
  writeFile("sitemap.xml", [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...locs,
    "</urlset>",
    "",
  ].join("\n"));
  return locs.length;
}

export function emitRobots() {
  writeFile("robots.txt", [
    "User-agent: *",
    "Allow: /",
    "",
    `Sitemap: ${origin()}/sitemap.xml`,
    "",
  ].join("\n"));
}

export function emitRedirects() {
  const base = fs.readFileSync(path.join(ROOT, "public", "_redirects"), "utf8").trimEnd();
  const legacy = legacyRedirects().map(({ from, to }) => `${from} ${to} 301`);
  writeFile("_redirects", [
    "# Canonical redirects for historical festival slugs.",
    "# Generated by scripts/build-seo.mjs from FESTIVAL_LEGACY_PATH_REDIRECTS — do not hand-edit.",
    ...legacy,
    "",
    "# Base rules, inherited verbatim from public/_redirects.",
    base,
    "",
  ].join("\n"));
  return legacy.length;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function replaceOrAppendHead(html, pattern, replacement) {
  return pattern.test(html)
    ? html.replace(pattern, replacement)
    : html.replace("</head>", `    ${replacement}\n  </head>`);
}

export function emitRouteHtml(routes) {
  const template = fs.readFileSync(path.join(DIST, "index.html"), "utf8");
  let written = 0;

  for (const route of routes) {
    const canonical = origin() + route.canonicalPath;
    let html = template;

    html = html.replace(/<title>[\s\S]*?<\/title>/, `<title>${escapeHtml(route.title)}</title>`);
    html = replaceOrAppendHead(html, /<meta name="description" content="[^"]*"\s*\/?>/,
      `<meta name="description" content="${escapeHtml(route.description)}" />`);
    html = replaceOrAppendHead(html, /<link rel="canonical" href="[^"]*"\s*\/?>/,
      `<link rel="canonical" href="${escapeHtml(canonical)}" />`);
    html = replaceOrAppendHead(html, /<meta property="og:title" content="[^"]*"\s*\/?>/,
      `<meta property="og:title" content="${escapeHtml(route.title)}" />`);
    html = replaceOrAppendHead(html, /<meta property="og:description" content="[^"]*"\s*\/?>/,
      `<meta property="og:description" content="${escapeHtml(route.description)}" />`);
    html = replaceOrAppendHead(html, /<meta property="og:url" content="[^"]*"\s*\/?>/,
      `<meta property="og:url" content="${escapeHtml(canonical)}" />`);

    const relative = route.path === "/" ? "index.html" : `${route.path.replace(/^\//, "")}/index.html`;
    writeFile(relative, html);
    written += 1;
  }

  return written;
}

function main() {
  if (!fs.existsSync(DIST)) {
    console.error("build-seo: dist/ not found — run `vite build` first.");
    process.exit(1);
  }
  const routes = publicRoutes();
  const count = emitSitemap(routes);
  emitRobots();
  console.log(`build-seo: sitemap ${count} URLs, robots.txt written.`);
  const redirectCount = emitRedirects();
  console.log(`build-seo: ${redirectCount} legacy 301s written ahead of the base rules.`);
  const htmlCount = emitRouteHtml(routes);
  console.log(`build-seo: ${htmlCount} route HTML files written.`);
}

main();
